### ISSUE TITLE
Request compilation

### ISSUE THREAD

**Issue by cgapk123** [VD42/UE4TextExtractor#1]
Please provide the exe executable program

**Comment by VD42** [comment]
Latest version: https://github.com/VD42/UE4TextExtractor/releases/download/0.5/UE4TextExtractor.exe
All releases available on this page: https://github.com/VD42/UE4TextExtractor/releases

**Comment by cgapk123** [comment]
Thank you
how can re-import the modified txt to .uasset /.uexp?

**Comment by cgapk123** [comment]
> 最新版本：[https](https://github.com/VD42/UE4TextExtractor/releases/download/0.5/UE4TextExtractor.exe)
> : [//github.com/VD42/UE4TextExtractor/releases/download/0.5/UE4TextExtractor.exe](https://github.com/VD42/UE4TextExtractor/releases)本页上的所有版本：[https](https://github.com/VD42/UE4TextExtractor/releases/download/0.5/UE4TextExtractor.exe) : [//github.com/VD42/UE4TextExtractor/releases](https://github.com/VD42/UE4TextExtractor/releases)

谢谢您
如何将修改后的txt重新导入到.uasset /.uexp？

**Comment by VD42** [comment]
You don't. But it's not needed anyway. You can create .locres file from .txt right now with external utility LocResTools.exe from https://github.com/VD42/UE4Tools/raw/master/UE4Tools.zip (In the future releases of UE4TextExtractor.exe this feature will be built into the program). A game can load .locres files from directories Content\\Localization\\Game\\{lang} or something like this (I don't remember specific details, better ask someone else about .locres files locations).

Using LocResTools.exe for example: `LocResTools.exe pack "MyGame\Content\Localization\Game\en\Game.locres" "Game.locres.txt"`.

**Comment by cgapk123** [comment]
Thanks, sorry, I still want to know Is there any tool to quickly edit font .uasset and .uexp files?
I need to add my own characters that Japanese alphabet doesnt

**Comment by VD42** [comment]
No universal simple tools or methods for this, as I know.

**Comment by cgapk123** [comment]
You know where there is a tutorial guide

**Comment by VD42** [comment]
Unfortunately I don't have any links on tutorials for fonts, but method for textures (for example: http://eggzero.serv.pink/octopath/OctopathMod.html, "Texture Swapping" part, video: https://www.youtube.com/watch?v=_EhwNMKmqHA&t=2985s) may basically work for fonts, I suppose.

**Comment by cgapk123** [comment]
Okay, it looks troublesome, thank you
