### ISSUE TITLE
Texts Not Extracted from Some .uasset Files !

### ISSUE THREAD

**Issue by 0xOCS** [VD42/UE4TextExtractor#10]
Hi VD42. First of all, thank you very much for presenting this unique tool to us. However, while testing it in a game, I noticed that it doesn't extract text from a few files, can you help me with this? I think you need to make a small fix.

Thank you in advance.
[sample.zip](https://github.com/VD42/UE4TextExtractor/files/11915622/sample.zip)

![sample](https://github.com/VD42/UE4TextExtractor/assets/42740919/1943eeea-f9de-4965-9a9b-af7ed660156a)

**Comment by VD42** [comment]
Unfortunately, in this file developers used some kind of their own localization system and not UE4 built-in system. This text most likely cannot be translated using locres-file.

**Comment by 0xOCS** [comment]
> Unfortunately, in this file developers used some kind of their own localization system and not UE4 built-in system. This text most likely cannot be translated using locres-file.

I think it will work if we include these titles in locres.
![headd](https://github.com/VD42/UE4TextExtractor/assets/42740919/464c7e6b-082b-4dfc-86fc-956b64c11bbf)

**Comment by VD42** [comment]
You can manually add this text to txt-file (use https://vd42.net/crc32.html for CRC32 calc) for test. Something like this:

```
=>{}

=>[PreviewText_6_DD6280FF4D518EEB8B4892A450C68321][4263249001]
This is how the subtitles will look in-game.

=>[Speaker_5_72C0C9C24C84E6540BC5E888D7C308B7][2849205871]
Speaker: 

Other texts
```

But without knowing namespace (it can be not empty), source strings (it can be not english) for CRC32 and actual algorithm of localization very unlikely it's gonna work.

**Comment by 0xOCS** [comment]
> You can manually add this text to txt-file (use https://vd42.net/crc32.html for CRC32 calc) for test. Something like this:
> 
> ```
> =>{}
> 
> =>[PreviewText_6_DD6280FF4D518EEB8B4892A450C68321][4263249001]
> This is how the subtitles will look in-game.
> 
> =>[Speaker_5_72C0C9C24C84E6540BC5E888D7C308B7][2849205871]
> Speaker: 
> 
> Other texts
> ```
> 
> But without knowing namespace (it can be not empty), source strings (it can be not english) for CRC32 and actual algorithm of localization very unlikely it's gonna work.

I would be grateful if you could make an external tool to extract texts in this way.

**Comment by VD42** [comment]
Unfortunately I don't have time to do it.

**Comment by 0xOCS** [comment]
> Unfortunately I don't have time to do it.

I understand, but it will be difficult to do this without you. Thank you for your time. Take care of yourselves.
