### ISSUE TITLE
Some .txt are not converted to locres

### ISSUE THREAD

**Issue by Saipan0** [VD42/UE4TextExtractor#11]
Hi, first of all thank you for your work. The tool always works but I have problems converting the txt to locres. It always works but with some txts it doesn't work. I'll attach the txt below if you can take a look at it, maybe it needs to be updated? Thanks anyway for your work :)

[texts_to_locres.txt](https://github.com/VD42/UE4TextExtractor/files/12707423/texts_to_locres.txt)

**Comment by VD42** [comment]
Part

```
=>{1EEBAF9744C9536D019BD58FB763BED6}

=>[As your eyes roll, you hear Carla moaning out loud,
screaming as she cums too.][892473462]
D

=>{DFAB99994222D36C465C25A1CFC097E6}

=>[English US][505817836]
pt-br
```

on the end of file looks wrong. Try to remove it (or just use corrected [texts_to_locres.txt](https://github.com/VD42/UE4TextExtractor/files/12708105/texts_to_locres.txt)).

**Comment by Saipan0** [comment]
Thank you very much it worked perfectly. Before closing the post, a confirmation question. The problem was the lines where there is no text?

=>{1EEBAF9744C9536D019BD58FB763BED6}

=>{DFAB99994222D36C465C25A1CFC097E6}

**Comment by VD42** [comment]
Not exactly, issue with

```
=>[As your eyes roll, you hear Carla moaning out loud,
screaming as she cums too.][892473462]
```

because Text Key is not expected new lines. Second Text Key (`English US`) also looks wrong, usually it's looks like `DFAB99994222D36C465C25A1CFC097E6` and I think they're not correctly parsed and some shifting happened. That is, Text Key is parsed as a Namespace (`=>{1EEBAF9744C9536D019BD58FB763BED6}` and `=>{DFAB99994222D36C465C25A1CFC097E6}`), text itself as Text Key and some garbage as text.

If it is known which file text
```
As your eyes roll, you hear Carla moaning out loud,
screaming as she cums too.
```
might сame from, I can try to fix it.

**Comment by Saipan0** [comment]
ok ok that's fine.
The text is found in the uexp file, which I attach

[File.zip](https://github.com/VD42/UE4TextExtractor/files/12709827/File.zip)

However, your tool has always worked. With so many games translated only two or three didn't work. Maybe the problem was the same because of a few sentences.

**Comment by VD42** [comment]
https://github.com/VD42/UE4TextExtractor/releases/download/0.18/UE4TextExtractor.exe - new version with custom raw text signatures feature. You can add modifier `-raw-text-signatures=SnowfallScriptAsset` to extract command (for example `UE4TextExtractor.exe "C:\MyGame\Content\Paks\unpacked" "C:\MyGame\Content\Paks\texts.txt" -raw-text-signatures=SnowfallScriptAsset`) and text from files that contain `SnowfallScriptAsset` assets (as file in attachment) will be processed.

**Comment by Saipan0** [comment]
A thousand thanks. I'll let you know if I find anything else. Good day. And thank you again :)
