### ISSUE TITLE
Texts in uexp file not detected

### ISSUE THREAD

**Issue by Saipan0** [VD42/UE4TextExtractor#12]
Hi, I have some texts inside a uexp file but they are not detected even using -all-uexps

[File.zip](https://github.com/VD42/UE4TextExtractor/files/13285032/File.zip)

I also tried to see the -raw-text-signatures= function but I couldn't.
I looked at the guide, but it's difficult for me for the first time :(
[https://github.com/VD42/UE4TextExtractor/blob/master/RAW_TEXT_SIGNATURES.md](url)
In the link, you had searched for SnowfallScriptAsset, but for me it's the first time I've searched in hexadecimal files, seeing the file, could you tell me which is the right string in your opinion?
Just to understand and learn. Thank you

Thanks for your help

**Comment by VD42** [comment]
I think you can use option `-raw-text-signatures=LevelSequence` (for example: `UE4TextExtractor.exe "C:\MyGame\Content\Paks\unpacked" "C:\MyGame\Content\Paks\texts.txt" -raw-text-signatures=LevelSequence`).

**Comment by Saipan0** [comment]
> I think you can use option `-raw-text-signatures=LevelSequence` (for example: `UE4TextExtractor.exe "C:\MyGame\Content\Paks\unpacked" "C:\MyGame\Content\Paks\texts.txt" -raw-text-signatures=LevelSequence`).

I looked up LevelSequence and I think I got it.
It works perfectly. I'll try with other files. Thanks you
