### ISSUE TITLE
Not all

### ISSUE THREAD

**Issue by ivann142** [VD42/UE4TextExtractor#2]
Hello, i try test this on game (Carnal Instinct) and that prog extract not all text. Is it possible to fix this?

**Comment by VD42** [comment]
Трудно сказать без примеров файлов с текстом, который не распознаётся.

**Comment by ivann142** [comment]
Да там много чего не распаёзнается и я не могу понять почему. Это варианты выборов или обычные стоковые диалоги (нпс без имён)

**Comment by ivann142** [comment]
[123.zip](https://github.com/VD42/UE4TextExtractor/files/7020984/123.zip) Ну в этих файлах допустим ни чего не распознёется и это далеко не всё)

**Comment by ivann142** [comment]
Я могу вам скинуть все файлы а вы можете их посмотреть или как?

**Comment by VD42** [comment]
Одного примера пока достаточно, попробую сначала разобраться с файлами из архива 123.zip.

**Comment by ivann142** [comment]
Я могу позже сделать файл+текст (примеры), если вы не сможете разобраться в этом.

**Comment by VD42** [comment]
Не нужно, если выяснится, что строки в файлах из архива 123.zip не могут быть локализованы с помощью locres-файлов (т.е. будут совсем не в том формате, что поддерживает программа), то моя программа не подойдёт для перевода, нужно будет искать какой-нибудь другой способ. Если же это будут строки в нужном формате, то я поправлю программу и, скорее всего, она заработает для всех или почти всех файлов.

**Comment by ivann142** [comment]
Хм, хорошо буду ждать результа. Очень хотелось бы конечно чтобы всё заработало с помощью вашей проги)

**Comment by VD42** [comment]
К сожалению, строки из присланных файлов непохожи на те, что можно локализовать с помощью locres-файла, поэтому моя программа для перевода игры не подойдёт.

**Comment by ivann142** [comment]
Обидно, других варик я не знаю. Что ж будем искать)
