### ISSUE TITLE
please help me

### ISSUE THREAD

**Issue by nonamebatbai** [VD42/UE4TextExtractor#4]
after extracting text.uexp file into text_to_locres.txt, how to compress text_to_locres.txt file into text.uexp file?

**Comment by nonamebatbai** [comment]
> [#1 (comment)](https://github.com/VD42/UE4TextExtractor/issues/1#issuecomment-844805620)

thank you very much . but there are still some text.uexp files of new games that cannot be decompressed eg life is strange true colors . Are you planning to upgrade the tool?

**Comment by VD42** [comment]
I can say more specific if I see examples of files with text  that not extracting. But usually this text cannot be localized using locres file.
