### ISSUE TITLE
Several questions and problems

### ISSUE THREAD

**Issue by enarkay** [VD42/UE4TextExtractor#9]
Thank you for your wonderful program, it is helping me a lot for UE games that do not have a localization folder.
However, I ran into several problems and have some questions to ask.

**Q1)** In your command line usage description, you tell us to use the -old parameter in case of an old-version of locres. What exactly is an 'old' version of locres, and how do I know if the locres file version is old or not? For example, do I determine it by the game's Unreal Game engine version?

**Q2)** I've read through all the other issues created on the github page to learn that games which the program does not extract any texts from, are games that cannot be localized by this program. I understand that. But I have problems with games that the program can extract texts from, but does NOT have a localization folder.

For example, a steam game called "The Devil Inside Us : Roots of Evil", which you can download the free demo to test it out for yourself, does not reflect the locres file created from UE4TextExtractor.
https://store.steampowered.com/app/1543520/Devil_Inside_Us_Roots_of_Evil/

- Using the program to extract texts from the unpacked contents of the .pak file DOES create a locres file.
- But there is no localization folder inside the Content folder of the game.
- So I created the folder directory according to the general usage as the following : **Satanic5\Content\Localization\Game\en**
- Then, I placed the Game.locres created from the program and with edited texts saying "test" into the game
- However, the edited texts are not reflected at all and the game just shows the original texts

Is there a way to solve this problem? Perhaps, instead of simply manually adding a **Content\Localization\Game\en\Game.locres** file, which the game seems to be failing to read, I also need to somehow generate and add a **locmeta** file as well?

For your easier reference and testing, I am attaching the following
: unedited Game.locres created from the program (**Game_original.locres**)
: edited Game.locres which I replace some original texts with "test" (**Game_edited.locres**)
: _p.pak file with the edited Game.locres (**Satanic5-WindowsNoEditor_p.pak**)
: a screenshot of which part of the game texts I edited - for the purpose of easy testing, I edited the texts that pop up at the very start of the game

![image](https://github.com/VD42/UE4TextExtractor/assets/7910166/a77d756b-7c71-463a-afbe-dbcbc705d1b6)
[attachment.zip](https://github.com/VD42/UE4TextExtractor/files/11781726/attachment.zip)

**Comment by VD42** [comment]
Q1) UE 4.15 and older can load only "old" locres-files. UE 4.16 and newer can load any locres-files generated from my tool, but "new" locres-files smaller because de-duplication feature.

Q2) I'll check UE source code about localization files lookup algorithm and give answer after few days. I suppose that can be configured using ini-files.

**Comment by enarkay** [comment]
Thank you very much for such clear answers and planning to invest your precious time to look into the issue, I will patiently await your reply :)

**Comment by enarkay** [comment]
> Q1) UE 4.15 and older can load only "old" locres-files. UE 4.16 and newer can load any locres-files generated from my tool, but "new" locres-files smaller because de-duplication feature.
> 
> Q2) I'll check UE source code about localization files lookup algorithm and give answer after few days. I suppose that can be configured using ini-files.

Thank you very much for such clear answers and planning to invest your precious time to look into the issue, I will patiently await your reply :)

**Comment by VD42** [comment]
I just put `Game.locres` (edited version) in `Devil Inside Us Roots of Evil Demo\Satanic5\Content\Localization\Game\en` and it's working:

<img width="1920" alt="image_2023-06-19_19-53-29" src="https://github.com/VD42/UE4TextExtractor/assets/1012077/9a132e7c-8907-4370-bbbc-9ae79bbdf746">

Maybe full game is somehow different using localization files but I recommend deleting everything added to game folder and try again only with edited version of `Game.locres` file.

**Comment by enarkay** [comment]
No, you're right. I've tried doing the same and it works. Since I've more than triple checked both before I sent you everything and once again now, to make sure that everything was made properly, I think the game is preventing the patch file (_p.pak) from loading and reflecting the files inside it. I guess I will just have to look for a way to get around this protection/prevention. Thank you very very much for your help :)

**Comment by enarkay** [comment]
Would you by any chance have any solution or knowledge regarding this problem? I've found that adding a "-openfilelog" parameter to the start option of the game can help with circumventing mod loading protection, but it looks like that doesn't work in this case and I'm practically at a dead end at this point.

While I will always have the option of just not repacking the modded files into a patch file (***_p.pak) and directly adding in folders and files like your test above, I would certainly prefer the patch file option since I may have quite a number and size of modded files depending on the games, such as font replacements, edited textures, and other uassets with strings missing from a locres file.

**Comment by VD42** [comment]
I used my old pak-file tool (https://github.com/VD42/UE4Tools) and it works too (I attached created pak-file). I checked different mount points and `../../../`, `../../../Satanic5/`, `../../../Satanic5/Content/`, `../../../Satanic5/Content/Localization/` working just fine but `../../../Satanic5/Content/Localization/Game/` and `../../../Satanic5/Content/Localization/Game/en/` not working at all. If your packing tool not supporting custom mount point, place any file (`placeholder.txt` for example) in base folder containing files for replace (togerher with `Satanic5` folder).

[Satanic5-WindowsNoEditor_p.zip](https://github.com/VD42/UE4TextExtractor/files/11798972/Satanic5-WindowsNoEditor_p.zip)

**Comment by enarkay** [comment]
http://fluffyquack.com/tools/unrealpak.rar

I have so far been using the above tool for packing any and all UE4 engine game patch _p.pak files,
and as we discussed so far, neither the compressed nor the uncompressed option with this tool seems to create a working patch file to reflect the edited texts.

So I thought I'd give your tool a try, and ran the command "PakTools.exe help" to see how your tool works :

PakTools.exe unpack <path_to_pak> <output_folder>
PakTools.exe pack <path_to_pak> <input_folder> <mount_pount>


While I can see how the unpack command works,
and the <path_to_pak> <input_folder> part for the pack command,
what exactly is a <mount_pount>?

- what is its feature?
- is it optional or mandatory?
- how do I figure out what to put in <mount_pount>?
- and will this tool work for all UE4 games? perhaps even for UE5 games?

**Comment by VD42** [comment]
As I said before, you can use UnrealPak, but place placeholder file in base folder (example in attach).

[Satanic5-WindowsNoEditor_p.zip](https://github.com/VD42/UE4TextExtractor/files/11801772/Satanic5-WindowsNoEditor_p.zip)

**Comment by enarkay** [comment]
Thank you very much, your example attachment made it really clear what I need to do. I just cannot thank you enough for all the trouble and annoyance you had to go through to help me out. Huge words of thanks, and I hope you have a great week!

Just in case you have anything to add, I won't close the issue right away, but you may close it anytime you want from now on :)
